-- Selects movie titles.
-- The WHERE clause checks if a movie's ID is present in a list of IDs.
-- This list is generated by finding the intersection of two sets of movie IDs:
-- 1. All movies starring Bradley Cooper.
-- 2. All movies starring Jennifer Lawrence.
-- The INTERSECT operator returns only the IDs that exist in both sets.
SELECT title FROM movies WHERE id IN (
    SELECT movie_id FROM stars
    JOIN people ON stars.person_id = people.id
    WHERE name = 'Bradley Cooper'
    INTERSECT
    SELECT movie_id FROM stars
    JOIN people ON stars.person_id = people.id
    WHERE name = 'Jennifer Lawrence'
);
