-- Selects the unique names of people.
-- Joins 'people' and 'stars' to link actors to their movies.
-- The first WHERE clause filters this list to only include people who starred in a movie...
-- ...whose ID is in the list generated by the subquery.
-- The subquery finds all movie IDs for movies starring the specific Kevin Bacon (born in 1958).
-- The final AND clause excludes Kevin Bacon himself from the results.
SELECT DISTINCT name FROM people
JOIN stars ON people.id = stars.person_id
WHERE movie_id IN (
    SELECT movie_id FROM stars
    JOIN people ON stars.person_id = people.id
    WHERE name = 'Kevin Bacon' AND birth = 1958
) AND name != 'Kevin Bacon';
